export default function renderContentfulImports(localization: boolean = false): string {
  if (localization) {
    return `
    // THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

    import { Entry as ContentfulEntry, ContentfulCollection} from 'contentful'
    import { Document } from '@contentful/rich-text-types'

    export interface Entry<T> extends ContentfulEntry<T> {
      fields?: T
    }

    export interface EntryCollection<T> extends ContentfulCollection<Entry<T>> {
      errors?: Array<any>
      includes?: any
      stringifySafe(replacer?: any, space?: any): string
    }
  `
  }

  return `
    // THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

    import { Asset, Entry  as ContentfulEntry, ContentfulCollection} from 'contentful'
    import { Document } from '@contentful/rich-text-types'

    export interface Entry<T> extends ContentfulEntry<T> {
      fields?: T
    }

    export interface EntryCollection<T> extends ContentfulCollection<Entry<T>> {
      errors?: Array<any>
      includes?: any
      stringifySafe(replacer?: any, space?: any): string
    }
  `
}
